Update sorting util to be more Python 3 friendly
In Python 3, implicit dictionary comparison is not allowed.

>>> {'a':1} < {'b':2}
Traceback (most recent call last):
TypeError: unorderable types: dict() < dict()

In our current sorting utility, equality in the key field
will lead to sorting against the dictionary. Using the builtin
priority queue requires implementing the __lt__ magic function.
The present implementation seeks to maintain current behavior
in a py2/3 compatible manner. Future changes can be used to
port the job manager behavior by modifying the comparison.

PiperOrigin-RevId: 210567344